# kcl-config.yaml
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-annotation
spec:
  # EDIT THE SOURCE!
  # This should be your KCL code which preloads the `ResourceList` to `option("items")
  source: |
    [resource | {if resource.kind == "Deployment": metadata.annotations: {"managed-by" = "helm-kcl-plugin"}} for resource in option("items")]

repositories:
  - name: workload
    path: ./workload-charts
  # - name: nginx-ingress
  #   url: https://github.com/nginxinc/kubernetes-ingress/tree/v3.1.0/deployments/helm-chart
